DISPLAY_W = 960
DISPLAY_H = 540
FPS = 30

DATA_FONT_SIZE = 18
DATA_FONT_COLOR = (0, 0, 0)
BG_FILENAME = r'assets/bg.png'

PIPE_UPPER_FILENAME = r'assets/pipe_upper.png'
PIPE_LOWER_FILENAME = r'assets/pipe_lower.png'
PIPE_SPEED = 70/1000
PIPE_DONE = 0
PIPE_MOVING = 1
PIPE_UPPER = 1
PIPE_LOWER = 0

PIPE_ADD_GAP = 160
PIPE_MIN = 80
PIPE_MAX = 500
PIPE_START_X = DISPLAY_W
PIPE_GAP_SIZE = 160
PIPE_FIRST = 400

BIRD_FILENAME = r'assets/bird.png'
BIRD_START_SPEED = -0.32
BIRD_START_X = 200
BIRD_START_Y = 200
BIRD_ALIVE = 1
BIRD_DEAD = 0
GRAVITY = 0.001

GENERATION_SIZE = 60